[project]
name = "transcript-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-api-python-client",
    "youtube-transcript-api",
    "python-dotenv",
    "tqdm",
    "ruff>=0.9.9",
]
